Description of pldapsDefaultTrialFunction
Home > PLDAPS > SupportFunctions > pldapsDefaultTrialFunction.m
pldapsDefaultTrialFunction
PURPOSE
SYNOPSIS
function pldapsDefaultTrialFunction(p,state)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
pds.audio.clearBuffer pds.audio.clearBuffer(p) stops audio output of files setup with pds.audio.setup(p)
pds.behavior.reward.cleanUpandSave pds.behavior.reward.cleanUpandSave(p) clean up after a trial
pds.behavior.reward.give pds.behavior.reward.give(p, amount) give a certaim amount of reward
pds.behavior.reward.trialSetup pds.behavior.reward.trialSetup(p) allocate memory for use during the trial
pds.datapixx.adc.cleanUpandSave pds.datapixx.adc.prepareTrial clean up after the trial
pds.datapixx.adc.getData pds.datapixx.adc.getData getData from the Datapixx buffer
pds.datapixx.adc.trialSetup pds.datapixx.adc.trialSetup setup everything for a trial
pds.datapixx.flipBit pds.datapixx.flipBit flip a bit on the digital out of the Datapixx
pds.datapixx.strobe pds.datapixx.strobe strobes a 16 Bit word from the datapixx
pds.eyelink.getQueue pds.eyelink.getQueue get data samples from eyelink
pds.eyelink.saveQueue pds.eyelink.saveQueue prunes unused samples and unneeded fields
pds.eyelink.startTrial pds.eyelink.startTrial allocate and clear buffer for the next trial
pds.eyelink.startTrialPrepare pds.eyelink.startTrialPrepare prepare the next trial
pds.keyboard.clearBuffer pds.git.clearBuffer clear the keyboard queue
pds.pldaps.draw.screenPlot
pds.plexon.spikeserver.getSpikes pds.plexon.spikeserver.getSpikes get data from the spikeserver
This function is called by:
eyelinkTimingTest eyelinkTimingTest pldaps trial state function to test the time delay of the eyelink system with
eyelinkTimingTestDigital eyelinkTimingTest pldaps trial state function to test the time delay of the eyelink system with
screenTimingTest screenTimingTest screenTimingTest is a pldaps stimulus to test the physical delay of the onset of a stimulus on the screen to
plain plain a plain stimulus file for use with a pldaps class. This file
PARAMETER USAGE INFORMATION
This function uses these parameters:
.datapixx.use: 263 341 370 379 404 417 enable control of VPixx devices
.display.bgColor: 128 129 130 230 231 232 390 391 background color. Can be changed during trial
.display.clut.blackbg: 147 149 151
.display.clut.cursor: 166
.display.clut.eyepos: 162
.display.clut.redbg: 153
.display.clut.window: 134
.display.ctr: 134
.display.frate: 212 213
.display.ifi: 145 147 147 149 306 312
.display.movie.create: 208 toggle movie creation
.display.movie.frameRate: 212 213 frame rate of the movie.
.display.movie.ptr: 220
.display.overlayptr: 134 161 165 235 236 310
.display.pHeight: 308
.display.pWidth: 308
.display.ptr: 129 174 191 206 220 231 235 390 393 403
.display.w2px: 308 309
.event.TRIALEND: 418
.event.TRIALSTART: 381
.eyeX: 161
.eyeY: 161
.eyelink.events: 490 490
.eyelink.use: 486 use the eyelink moduke
.iFrame: 48 138 141 141 169 172 213 239 482 483
.keyboard.codes.dKey: 79
.keyboard.codes.mKey: 57
.keyboard.codes.pKey: 69
.keyboard.codes.qKey: 73
.keyboard.firstPressQ: 50 56 57 69 73 79
.keyboard.nCodes: 275 276 277 278
.keyboard.pressedQ: 44 49
.keyboard.samples: 46
.mouse.cursorSamples: 98 99 102 103 165
.mouse.samples: 92 98 99 101 101 165
.mouse.use: 90 164 281 434 collect and store mouse positions
.mouse.useAsEyepos: 96 toggle use of mouse to set eyeX and eyeY
.pldaps.draw.cursor.use: 164 enable drawing of the mouse cursor.
.pldaps.draw.eyepos.use: 160 enable drawing of the eye position.
.pldaps.draw.framerate.data: 140 145 153
.pldaps.draw.framerate.location: 308 location (XY) of the plot in degrees of visual angle.
.pldaps.draw.framerate.nFrames: 153 307 311
.pldaps.draw.framerate.nSeconds: 306 number of seconds to show the history for
.pldaps.draw.framerate.sf: 147 149 151 153
.pldaps.draw.framerate.sf.xlims: 147 149 151
.pldaps.draw.framerate.show: 143 draw the framerate. need use to be enabled as well
.pldaps.draw.framerate.size: 309 size (XY) of the plot in degrees of visual angle.
.pldaps.draw.framerate.use: 138 305 set to true to collect data needed to show framerate.
.pldaps.draw.grid.tick_line_matrix: 134
.pldaps.draw.grid.use: 133 enable drawing of the grid
.pldaps.draw.photodiode.dataEnd: 173
.pldaps.draw.photodiode.everyXFrames: 169 will be shown every nth frame
.pldaps.draw.photodiode.rect: 174
.pldaps.draw.photodiode.use: 169 249 421 enable drawing the photodione square
.pldaps.experimentAfterTrialsFunction: 30 31 a function to be called after each trial.
.pldaps.eyeposMovAv: 97 101 average the eyeposition (.eyeX and .eyeY) over this many samples.
.pldaps.iTrial: 381 418 479 trial number. cannot be changed by the user
.pldaps.lastBgColor: 128 230
.pldaps.maxFrames: 246 247 250 271 272 274 275 276 277 278 283 284 285
.pldaps.trialStates.experimentAfterTrials: 29 called after each trial.
.pldaps.trialStates.frameDraw: 8 called every frame for drawing command.
.pldaps.trialStates.frameDrawingFinished: 14 called every frame after drawing.
.pldaps.trialStates.frameFlip: 18 called every frame to flip the buffers.
.pldaps.trialStates.framePrepareDrawing: 6 called every frame to prepare drawing.
.pldaps.trialStates.frameUpdate: 4 called every frame to update input.
.pldaps.trialStates.trialCleanUpandSave: 26 called at the end of the trial.
.pldaps.trialStates.trialPrepare: 24 called before each trial for synchronization
.pldaps.trialStates.trialSetup: 22 called before each trial for data allocation.
.plexon.spikeserver.use: 452 toggle use of our plexon spikeserver
.stimulus.eyeW: 162 166
.timing.flipTimes: 141 141 239 482
.timing.frameStateChangeTimes: 483
.trstart: 239 395 397 407
.ttime: 172 398
This function assigns these parameters:
.datapixx.datapixxstoptime: 405
.datapixx.unique_number_time: 372
.eyeX: 98 102
.eyeY: 99 103
.eyelink.events: 490
.eyelink.sampleIds: 489
.eyelink.samples: 488
.framePostLastDrawIdleCount: 241
.framePreLastDrawIdleCount: 240
.iFrame: 206 403
.keyboard.firstPressQ: 42
.keyboard.firstPressSamples: 50 275 444
.keyboard.firstReleaseSamples: 51 276 445
.keyboard.lastPressSamples: 52 277 446
.keyboard.lastReleaseSamples: 53 278 447
.keyboard.pressedQ: 42
.keyboard.pressedSamples: 49 274 443
.keyboard.samples: 46 47 48 49 50 51 52 53 270 441 442 443 444 445 446 447
.keyboard.samplesFrames: 48 272 442
.keyboard.samplesTimes: 47 271 441
.mouse.buttonPressSamples: 95 284 436
.mouse.cursorSamples: 94 283 435
.mouse.samples: 92 93 94 95 286 435 436 437
.mouse.samplesTimes: 93 285 437
.pldaps.draw.framerate.data: 140 141 307
.pldaps.draw.framerate.nFrames: 306
.pldaps.draw.framerate.sf: 315
.pldaps.draw.framerate.sf.ylims: 145
.pldaps.draw.photodiode.dataEnd: 172 173 251 422
.pldaps.lastBgColor: 130 232 391
.pldaps.quit: 70 77 control expeiment during a trial.
.plexon.spikeserver.spikeCount: 297
.stimulus.timeLastFrame: 239 395
.timing.datapixxPreciseTime: 265
.timing.datapixxStartTime: 380
.timing.datapixxTRIALEND: 418
.timing.datapixxTRIALSTART: 381
.timing.flipTimes: 206 246 403 482
.timing.frameStateChangeTimes: 247 483
.timing.photodiodeTimes: 172 250 422
.timing.syncTimeDuration: 398
.trialend: 407
.trialnumber: 479
.trstart: 394
.ttime: 397
.unique_number: 375
SUBFUNCTIONS
frameUpdate
frameDraw
frameDrawingFinished
frameFlip
trialSetup
trialPrepare
cleanUpandSave
SOURCE CODE
function pldapsDefaultTrialFunction(p,state)
    switch state
        %frameStates
        case p.trial.pldaps.trialStates.frameUpdate
            frameUpdate(p);
        case p.trial.pldaps.trialStates.framePrepareDrawing
        %    framePrepareDrawing(p);
        case p.trial.pldaps.trialStates.frameDraw
            frameDraw(p);
        %case p.trial.pldaps.trialStates.frameIdlePreLastDraw
        %    frameIdlePreLastDraw(p);
        %case p.trial.pldaps.trialStates.frameDrawTimecritical;
        %    drawTimecritical(p);
        case p.trial.pldaps.trialStates.frameDrawingFinished;
            frameDrawingFinished(p);
        %case p.trial.pldaps.trialStates.frameIdlePostDraw;
        %    frameIdlePostDraw(p);
        case p.trial.pldaps.trialStates.frameFlip;
            frameFlip(p);
        %trialStates
        case p.trial.pldaps.trialStates.trialSetup
            trialSetup(p);
        case p.trial.pldaps.trialStates.trialPrepare
            trialPrepare(p);
        case p.trial.pldaps.trialStates.trialCleanUpandSave
            cleanUpandSave(p);
        %only availiable if p.trial.pldaps.trialMasterFunction = 'runModularTrial'
        case p.trial.pldaps.trialStates.experimentAfterTrials
            if ~isempty(p.trial.pldaps.experimentAfterTrialsFunction)
               h=str2func(p.trial.pldaps.experimentAfterTrialsFunction);
               h(p, state)
            end
    end
end
%%% get inputs and check behavior%%%
%---------------------------------------------------------------------%
    function frameUpdate(p)
        %%TODO: add buffer for Keyboard presses, nouse position and clicks.
        %Keyboard
        [p.trial.keyboard.pressedQ, p.trial.keyboard.firstPressQ, firstRelease, lastPress, lastRelease]=KbQueueCheck(); % fast
        if p.trial.keyboard.pressedQ || any(firstRelease)
    %         [p.trial.keyboard.pressedQ,  p.trial.keyboard.firstPressQ]=KbQueueCheck(); % fast
            p.trial.keyboard.samples = p.trial.keyboard.samples+1;
            p.trial.keyboard.samplesTimes(p.trial.keyboard.samples)=GetSecs;
            p.trial.keyboard.samplesFrames(p.trial.keyboard.samples)=p.trial.iFrame;
            p.trial.keyboard.pressedSamples(:,p.trial.keyboard.samples)=p.trial.keyboard.pressedQ;
            p.trial.keyboard.firstPressSamples(:,p.trial.keyboard.samples)=p.trial.keyboard.firstPressQ;
            p.trial.keyboard.firstReleaseSamples(:,p.trial.keyboard.samples)=firstRelease;
            p.trial.keyboard.lastPressSamples(:,p.trial.keyboard.samples)=lastPress;
            p.trial.keyboard.lastReleaseSamples(:,p.trial.keyboard.samples)=lastRelease;
        end
        if any(p.trial.keyboard.firstPressQ)
            if  p.trial.keyboard.firstPressQ(p.trial.keyboard.codes.mKey)
                  pds.behavior.reward.give(p);
%                 if p.trial.datapixx.use
%                     pds.datapixx.analogOut(p.trial.stimulus.rewardTime)
%                     pds.datapixx.flipBit(p.trial.event.REWARD,p.trial.pldaps.iTrial);
%                 end
%     %             p.trial.ttime = GetSecs - p.trial.trstart;
%                 p.trial.stimulus.timeReward(:,p.trial.stimulus.iReward) = [p.trial.ttime p.trial.stimulus.rewardTime];
%                 p.trial.stimulus.iReward = p.trial.stimulus.iReward + 1;
%                 PsychPortAudio('Start', p.trial.sound.reward);
    %         elseif  p.trial.keyboard.firstPressQ(p.trial.keyboard.codes.uKey)   % U = user selected targets
    %             p.trial.targUser = 1;
            elseif  p.trial.keyboard.firstPressQ(p.trial.keyboard.codes.pKey)   % P = pause
                p.trial.pldaps.quit = 1;
                ShowCursor;
    %             Screen('Flip', p.trial.display.ptr);
            elseif  p.trial.keyboard.firstPressQ(p.trial.keyboard.codes.qKey) % Q = quit
    %             Screen('Flip', p.trial.display.ptr);
    %             p = pdsEyelinkFinish(p);
    %             PDS.timing.timestamplog = PsychDataPixx('GetTimestampLog', 1);
                p.trial.pldaps.quit = 2;
                ShowCursor
            elseif  p.trial.keyboard.firstPressQ(p.trial.keyboard.codes.dKey) % d=debug
                    disp('stepped into debugger. Type return to start first trial...')
                    keyboard %#ok<MCKBD>
    %             dbstop if warning opticflow:debugger_requested;
    %             warning on opticflow:debugger_requested;
    %             warning('opticflow:debugger_requested','At your service!');
    %             warning off opticflow:debugger_requested;
    %             dbclear if warning opticflow:debugger_requested;
            end
        end
        % get mouse/eyetracker data
        if p.trial.mouse.use
            [cursorX,cursorY,isMouseButtonDown] = GetMouse(); % ktz - added isMouseButtonDown, 28Mar2013
            p.trial.mouse.samples = p.trial.mouse.samples+1;
            p.trial.mouse.samplesTimes(p.trial.mouse.samples)=GetSecs;
            p.trial.mouse.cursorSamples(1:2,p.trial.mouse.samples) = [cursorX;cursorY];
            p.trial.mouse.buttonPressSamples(:,p.trial.mouse.samples) = isMouseButtonDown';
            if(p.trial.mouse.useAsEyepos)
                if p.trial.pldaps.eyeposMovAv==1
                    p.trial.eyeX = p.trial.mouse.cursorSamples(1,p.trial.mouse.samples);
                    p.trial.eyeY = p.trial.mouse.cursorSamples(2,p.trial.mouse.samples);
                else
                    mInds=(p.trial.mouse.samples-p.trial.pldaps.eyeposMovAv+1):p.trial.mouse.samples;
                    p.trial.eyeX = mean(p.trial.mouse.cursorSamples(1,mInds));
                    p.trial.eyeY = mean(p.trial.mouse.cursorSamples(2,mInds));
                end
            end
        end
        %get analogData from Datapixx
        pds.datapixx.adc.getData(p);
        %get eyelink data
        pds.eyelink.getQueue(p);
        %get plexon spikes
%         pds.plexon.spikeserver.getSpikes(p);
    end %frameUpdate
%
%     function framePrepareDrawing(p)
%     end %framePrepareDrawing
    %% frameDraw
    function frameDraw(p)
        %this holds the code to draw some stuff to the overlay (using
        %switches, like the grid, the eye Position, etc
        %consider moving this stuff to an earlier timepoint, to allow GPU
        %to crunch on this before the real stuff gets added.
        %did the background color change? Usually already applied after
        %frameFlip, but make sure we're not missing anything
        if any(p.trial.pldaps.lastBgColor~=p.trial.display.bgColor)
            Screen('FillRect', p.trial.display.ptr,p.trial.display.bgColor);
            p.trial.pldaps.lastBgColor = p.trial.display.bgColor;
        end
        if p.trial.pldaps.draw.grid.use
            Screen('DrawLines',p.trial.display.overlayptr,p.trial.pldaps.draw.grid.tick_line_matrix,1,p.trial.display.clut.window,p.trial.display.ctr(1:2));
        end
        %draw a history of fast inter frame intervals
        if p.trial.pldaps.draw.framerate.use && p.trial.iFrame>2
            %update data
            p.trial.pldaps.draw.framerate.data=circshift(p.trial.pldaps.draw.framerate.data,-1);
            p.trial.pldaps.draw.framerate.data(end)=p.trial.timing.flipTimes(1,p.trial.iFrame-1)-p.trial.timing.flipTimes(1,p.trial.iFrame-2);
            %plot
            if p.trial.pldaps.draw.framerate.show
                %adjust y limit
                p.trial.pldaps.draw.framerate.sf.ylims=[0 max(max(p.trial.pldaps.draw.framerate.data), 2*p.trial.display.ifi)];
                %current ifi is solid black
                pds.pldaps.draw.screenPlot(p.trial.pldaps.draw.framerate.sf, p.trial.pldaps.draw.framerate.sf.xlims, [p.trial.display.ifi p.trial.display.ifi], p.trial.display.clut.blackbg, '-');
                %2 ifi reference is 5 black dots
                pds.pldaps.draw.screenPlot(p.trial.pldaps.draw.framerate.sf, p.trial.pldaps.draw.framerate.sf.xlims(2)*(0:0.25:1), ones(1,5)*2*p.trial.display.ifi, p.trial.display.clut.blackbg, '.');
                %0 ifi reference is 5 black dots
                pds.pldaps.draw.screenPlot(p.trial.pldaps.draw.framerate.sf, p.trial.pldaps.draw.framerate.sf.xlims(2)*(0:0.25:1), zeros(1,5), p.trial.display.clut.blackbg, '.');
                %data are red dots
                pds.pldaps.draw.screenPlot(p.trial.pldaps.draw.framerate.sf, 1:p.trial.pldaps.draw.framerate.nFrames, p.trial.pldaps.draw.framerate.data', p.trial.display.clut.redbg, '.');
            end
         end
         %draw the eyepositon to the second srceen only
         %move the color and size parameters to
         %p.trial.pldaps.draw.eyepos?
         if p.trial.pldaps.draw.eyepos.use
            Screen('Drawdots',  p.trial.display.overlayptr, [p.trial.eyeX p.trial.eyeY]', ...
            p.trial.stimulus.eyeW, p.trial.display.clut.eyepos, [0 0],0);
         end
         if p.trial.mouse.use && p.trial.pldaps.draw.cursor.use
            Screen('Drawdots',  p.trial.display.overlayptr,  p.trial.mouse.cursorSamples(1:2,p.trial.mouse.samples), ...
            p.trial.stimulus.eyeW, p.trial.display.clut.cursor, [0 0],0);
         end
         if p.trial.pldaps.draw.photodiode.use && mod(p.trial.iFrame, p.trial.pldaps.draw.photodiode.everyXFrames) == 0
%             photodiodecolor = p.trial.display.clut.window;
            photodiodecolor = [1 1 1];
            p.trial.timing.photodiodeTimes(:,p.trial.pldaps.draw.photodiode.dataEnd) = [p.trial.ttime p.trial.iFrame];
            p.trial.pldaps.draw.photodiode.dataEnd=p.trial.pldaps.draw.photodiode.dataEnd+1;
            Screen('FillRect',  p.trial.display.ptr,photodiodecolor, p.trial.pldaps.draw.photodiode.rect');
        end
    end %frameDraw
    %% frameIdlePreLastDraw
%     function frameIdlePreLastDraw(p)
%         %only execute once, since this is the only part atm, this is done at 0
%         if p.trial.framePreLastDrawIdleCount==0
%         else %if no one stepped in to execute we might as well skip to the next stage
%             p.trial.currentFrameState=p.trial.pldaps.trialStates.frameDrawTimecritical;
%         end
%     end %frameIdlePreLastDraw
%     function drawTimecritical(p)
%     end %drawTimecritical
    function frameDrawingFinished(p)
        Screen('DrawingFinished', p.trial.display.ptr,0,0);
%         Screen('DrawingFinished', p.trial.display.overlayptr);
        %if we're going async, we'd probably do the flip call here, right? but
        %could also do it in the flip either way.
    end %frameDrawingFinished
%     function frameIdlePostDraw(p)
%         if p.trial.framePostLastDrawIdleCount==0
%         else
%             p.trial.currentFrameState=p.trial.pldaps.trialStates.frameFlip;
%         end
%     end %frameIdlePostDraw
    function frameFlip(p)
%       if mod(p.trial.iFrame,3)==1
         p.trial.timing.flipTimes(:,p.trial.iFrame) = deal(Screen('Flip', p.trial.display.ptr,0));
%       end
         if p.trial.display.movie.create
             %we should skip every nth frame depending on the ration of
             %frame rates, or increase every nth frameduration by 1 every
             %nth frame
             if p.trial.display.frate > p.trial.display.movie.frameRate
                 thisframe = mod(p.trial.iFrame, p.trial.display.frate/p.trial.display.movie.frameRate)>0;
             else
                 thisframe=true;
             end
             if thisframe
                 frameDuration=1;
                 Screen('AddFrameToMovie', p.trial.display.ptr,[],[],p.trial.display.movie.ptr, frameDuration);
             end
         end
         %did the background color change?
         %we're doing it here to make sure we don't overwrite anything
         %but this tyically causes a one frame delay until it's applied
         %i.e. when it's set in frame n, it changes when frame n+1 flips
         %otherwise we could trust users not to draw before
         %frameDraw, but we'll check again at frameDraw to be sure
         if any(p.trial.pldaps.lastBgColor~=p.trial.display.bgColor)
             Screen('FillRect', p.trial.display.ptr,p.trial.display.bgColor);
             p.trial.pldaps.lastBgColor = p.trial.display.bgColor;
         end
         if p.trial.display.overlayptr ~= p.trial.display.ptr
            Screen('FillRect', p.trial.display.overlayptr,0);
         end
         p.trial.stimulus.timeLastFrame = p.trial.timing.flipTimes(1,p.trial.iFrame)-p.trial.trstart;
         p.trial.framePreLastDrawIdleCount=0;
         p.trial.framePostLastDrawIdleCount=0;
    end %frameFlip
    function trialSetup(p)
        p.trial.timing.flipTimes       = zeros(4,p.trial.pldaps.maxFrames);
        p.trial.timing.frameStateChangeTimes=nan(9,p.trial.pldaps.maxFrames);
        if(p.trial.pldaps.draw.photodiode.use)
            p.trial.timing.photodiodeTimes=nan(2,p.trial.pldaps.maxFrames);
            p.trial.pldaps.draw.photodiode.dataEnd=1;
        end
        %these are things that are specific to subunits as eyelink,
        %datapixx, mouse and should probabbly be in separarte functions,
        %but I have no logic/structure for that atm.
        %setup analogData collection from Datapixx
        pds.datapixx.adc.trialSetup(p);
        %call PsychDataPixx('GetPreciseTime') to make sure the clocks stay
        %synced
        if p.trial.datapixx.use
            [getsecs, boxsecs, confidence] = PsychDataPixx('GetPreciseTime');
            p.trial.timing.datapixxPreciseTime(1:3) = [getsecs, boxsecs, confidence];
        end
        %setup a fields for the keyboard data
%         [~, firstPress]=KbQueueCheck();
        p.trial.keyboard.samples = 0;
        p.trial.keyboard.samplesTimes=zeros(1,round(p.trial.pldaps.maxFrames*1.1));
        p.trial.keyboard.samplesFrames=zeros(1,round(p.trial.pldaps.maxFrames*1.1));
%         p.trial.keyboard.keyPressSamples = zeros(length(firstPressQ),round(p.trial.pldaps.maxFrames*1.1));
        p.trial.keyboard.pressedSamples=false(1,round(p.trial.pldaps.maxFrames*1.1));
        p.trial.keyboard.firstPressSamples = zeros(p.trial.keyboard.nCodes,round(p.trial.pldaps.maxFrames*1.1));
        p.trial.keyboard.firstReleaseSamples = zeros(p.trial.keyboard.nCodes,round(p.trial.pldaps.maxFrames*1.1));
        p.trial.keyboard.lastPressSamples = zeros(p.trial.keyboard.nCodes,round(p.trial.pldaps.maxFrames*1.1));
        p.trial.keyboard.lastReleaseSamples = zeros(p.trial.keyboard.nCodes,round(p.trial.pldaps.maxFrames*1.1));
        %setup a fields for the mouse data
        if p.trial.mouse.use
            [~,~,isMouseButtonDown] = GetMouse();
            p.trial.mouse.cursorSamples = zeros(2,round(round(p.trial.pldaps.maxFrames*1.1)));
            p.trial.mouse.buttonPressSamples = zeros(length(isMouseButtonDown),round(round(p.trial.pldaps.maxFrames*1.1)));
            p.trial.mouse.samplesTimes=zeros(1,round(round(p.trial.pldaps.maxFrames*1.1)));
            p.trial.mouse.samples = 0;
        end
        %%% Eyelink Toolbox Setup %%%
        %-------------------------------------------------------------------------%
        % preallocate for all eye samples and event data from the eyelink
        pds.eyelink.startTrial(p);
        %%% Spike server
        %-------------------------------------------------------------------------%
%         [p,spikes] = pds.plexon.spikeserver.getSpikes(p); %what are we dowing with the spikes???
        p.trial.plexon.spikeserver.spikeCount=0;
        pds.plexon.spikeserver.getSpikes(p); %save all spikes that arrives in the inter trial interval
        %%% prepare reward system
        pds.behavior.reward.trialSetup(p);
        %%% prepare to plot framerate history on screen
        if p.trial.pldaps.draw.framerate.use
            p.trial.pldaps.draw.framerate.nFrames=round(p.trial.pldaps.draw.framerate.nSeconds/p.trial.display.ifi);
            p.trial.pldaps.draw.framerate.data=zeros(p.trial.pldaps.draw.framerate.nFrames,1); %holds the data
            sf.startPos=round(p.trial.display.w2px'.*p.trial.pldaps.draw.framerate.location + [p.trial.display.pWidth/2 p.trial.display.pHeight/2]);
            sf.size=p.trial.display.w2px'.*p.trial.pldaps.draw.framerate.size;
            sf.window=p.trial.display.overlayptr;
            sf.xlims=[1 p.trial.pldaps.draw.framerate.nFrames];
            sf.ylims=  [0 2*p.trial.display.ifi];
            sf.linetype='-';
            p.trial.pldaps.draw.framerate.sf=sf;
        end
%         %setup assignemnt of eyeposition data to eyeX and eyeY
%         %first create the S structs for subsref.
%         % Got a big WTF on your face? read up on subsref, subsasgn and substruct
%         % we need this to dynamically access data deep inside a multilevel struct
%         % without using eval.
%         % different approach: have it set by the data collectors
%         % themselves?
    end %trialSetup
    function trialPrepare(p)
        %%% setup PsychPortAudio %%%
        %-------------------------------------------------------------------------%
        % we use the PsychPortAudio pipeline to give auditory feedback because it
        % has less timing issues than Beeper.m -- Beeper freezes flips as long as
        % it is producing sound whereas PsychPortAudio loads a wav file into the
        % buffer and can call it instantly without wasting much compute time.
        pds.audio.clearBuffer(p)
%TODO        %do we need this?
        if p.trial.datapixx.use
            Datapixx RegWrRd;
        end
        %%% Initalize Keyboard %%%
        %-------------------------------------------------------------------------%
        pds.keyboard.clearBuffer(p);
        %%% Eyelink Toolbox Setup %%%
        %-------------------------------------------------------------------------%
        % preallocate for all eye samples and event data from the eyelink
        pds.eyelink.startTrialPrepare(p);
        %%% START OF TRIAL TIMING %%
        %-------------------------------------------------------------------------%
        % record start of trial in Datapixx, Mac & Plexon
        % each device has a separate clock
        % At the beginning of each trial, strobe a unique number to the plexon
        % through the Datapixx to identify each trial. Often the Stimulus display
        % will be running for many trials before the recording begins so this lets
        % the plexon rig sync up its first trial with whatever trial number is on
        % for stimulus display.
        % SYNC clocks
%TODO move into a pds.plexon.startTrial(p) file. Also just sent the data along the trialStart flax, or a  least after?
        clocktime = fix(clock);
        if p.trial.datapixx.use
            for ii = 1:6
                p.trial.datapixx.unique_number_time(ii,:)=pds.datapixx.strobe(clocktime(ii));
            end
        end
        p.trial.unique_number = clocktime;    % trial identifier
        %TODO move into a pds.plexon.startTrial(p) file? Or is this a generic
%datapixx thing? not really....
        if p.trial.datapixx.use
            p.trial.timing.datapixxStartTime = Datapixx('Gettime');
            p.trial.timing.datapixxTRIALSTART = pds.datapixx.flipBit(p.trial.event.TRIALSTART,p.trial.pldaps.iTrial);  % start of trial (Plexon)
        end
%%check reconstruction
        %old
%                 p.trial.trstart = GetSecs;
        %new
        %ensure background color is correct
        Screen('FillRect', p.trial.display.ptr,p.trial.display.bgColor);
        p.trial.pldaps.lastBgColor = p.trial.display.bgColor;
        vblTime = Screen('Flip', p.trial.display.ptr,0);
        p.trial.trstart = vblTime;
        p.trial.stimulus.timeLastFrame=vblTime-p.trial.trstart;
        p.trial.ttime  = GetSecs - p.trial.trstart;
        p.trial.timing.syncTimeDuration = p.trial.ttime;
    end %trialPrepare
    function p = cleanUpandSave(p)
%TODO move to pds.datapixx.cleanUpandSave
        [p.trial.timing.flipTimes(:,p.trial.iFrame)] = deal(Screen('Flip', p.trial.display.ptr));
        if p.trial.datapixx.use
            p.trial.datapixx.datapixxstoptime = Datapixx('GetTime');
        end
        p.trial.trialend = GetSecs- p.trial.trstart;
%         [p.trial.timing.flipTimes(:,p.trial.iFrame)] = deal(Screen('Flip', p.trial.display.ptr));
        %do a last frameUpdate
        frameUpdate(p)
%TODO move to pds.datapixx.cleanUpandSave
        %clean up analogData collection from Datapixx
        pds.datapixx.adc.cleanUpandSave(p);
         if p.trial.datapixx.use
            p.trial.timing.datapixxTRIALEND = pds.datapixx.flipBit(p.trial.event.TRIALEND,p.trial.pldaps.iTrial);  % start of trial (Plexon)
        end
        if(p.trial.pldaps.draw.photodiode.use)
            p.trial.timing.photodiodeTimes(:,p.trial.pldaps.draw.photodiode.dataEnd:end)=[];
        end
        % if isfield(p, 'dp') % FIX ME
        %     p.dp = pds.datapixx.adcStop(p.dp);
        % end
        %% Flush KbQueue %%%
        KbQueueStop();
        KbQueueFlush();
        %will this crash when more samples where created than preallocated?
        % mouse input
        if p.trial.mouse.use
            p.trial.mouse.cursorSamples(:,p.trial.mouse.samples+1:end) = [];
            p.trial.mouse.buttonPressSamples(:,p.trial.mouse.samples+1:end) = [];
            p.trial.mouse.samplesTimes(:,p.trial.mouse.samples+1:end) = [];
        end
%         p.trial.keyboard.keyPressSamples(:,p.trial.keyboard.samples+1:end) = [];
        p.trial.keyboard.samplesTimes(:,p.trial.keyboard.samples+1:end) = [];
        p.trial.keyboard.samplesFrames(:,p.trial.keyboard.samples+1:end) = [];
        p.trial.keyboard.pressedSamples(:,p.trial.keyboard.samples+1:end) = [];
        p.trial.keyboard.firstPressSamples(:,p.trial.keyboard.samples+1:end) = [];
        p.trial.keyboard.firstReleaseSamples(:,p.trial.keyboard.samples+1:end) = [];
        p.trial.keyboard.lastPressSamples(:,p.trial.keyboard.samples+1:end) = [];
        p.trial.keyboard.lastReleaseSamples(:,p.trial.keyboard.samples+1:end) = [];
%TODO move to pds.plexon.cleanUpandSave
        % Get spike server spikes
        %---------------------------------------------------------------------%
        if p.trial.plexon.spikeserver.use
            try
                pds.plexon.spikeserver.getSpikes(p);
            catch me
                disp(me.message)
            end
        end
%             end
%             try
%                 [p, p.trial.plexon.spikeserver.spikes] = pds.plexon.spikeserver.getSpikes(p);
%
%                 if ~isempty(p.trial.spikeserver.spikes)
%                     plbit = p.trial.event.TRIALSTART + 2;
%                     t0 = find(p.trial.spikeserver.spikes(:,1) == 4 & p.trial.spikeserver.spikes(:,2) == plbit, 1, 'first');
%                     p.trial.plexon.spikeserver.spikes(:,4) = p.trial.plexon.spikeserver.spikes(:,4) - p.trial.plexon.spikeserver.spikes(t0,4);
% %                     PDS.spikes{p.j} = spikes;
%                 else
% %                     PDS.spikes{p.j} = []; % zeros size of spike matrix
%                     fprintf('No spikes. Check if server is running\r')
%                 end
%
%             catch me
%                 disp(me.message)
%             end
%         end
        %---------------------------------------------------------------------%
        p.trial.trialnumber   = p.trial.pldaps.iTrial;
        % system timing
        p.trial.timing.flipTimes      = p.trial.timing.flipTimes(:,1:p.trial.iFrame);
        p.trial.timing.frameStateChangeTimes    = p.trial.timing.frameStateChangeTimes(:,1:p.trial.iFrame-1);
%TODO move to pds.eyelink.cleanUpandSave
        if p.trial.eyelink.use
            [Q, rowId] = pds.eyelink.saveQueue(p);
            p.trial.eyelink.samples = Q;
            p.trial.eyelink.sampleIds = rowId; % I overwrite everytime because PDStrialTemps get saved after every trial if we for some unforseen reason ever need this for each trial
            p.trial.eyelink.events   = p.trial.eyelink.events(:,~isnan(p.trial.eyelink.events(1,:)));
        end
       %reward system
       pds.behavior.reward.cleanUpandSave(p);
        % Update Scope
    %     try
    %         pdsScopeUpdate(PDS,p.j)
    %     catch
    %         disp('error updating scope')
    %     end
    end %cleanUpandSave
check here date of last update.