Description of runModularTrial
Home > PLDAPS > @pldaps > runModularTrial.m
@pldaps/runModularTrial
PURPOSE
runModularTrial runs a single Trial by calling the functions defined in
SYNOPSIS
function p = runModularTrial(p, replay)
DESCRIPTION
runModularTrial    runs a single Trial by calling the functions defined in
            their substruct (found by pldaps.getModules) and the function
            defined in p.trial.pldaps.trialFunction through different states
 03/2013 jly   Wrote hyperflow
 03/2014 jk    Used jly's code to get the PLDAPS structure and frame it into a class
               might change to ASYNC buffer flipping. but won't for now.
 03/2016 jk    modular version
CROSS-REFERENCE INFORMATION
This function calls:
@pldaps/getModules add a requested Order: from -Inf allways first to 0 Default to after
@pldaps/replay replay replay a previously recorded experiment on screen
@pldaps/runStateforModules using cellfun might be slower than a for loop and does not guaranty
This function is called by:
PARAMETER USAGE INFORMATION
This function uses these parameters:
.display.ifi: 52 59 64
.flagNextTrial: 47
.iFrame: 59 68
.nextFrameTime: 59 63 64
.pldaps.iTrial: 59 trial number. cannot be changed by the user
.pldaps.maxPriority: 33 71 Switch to PTB to maxpriority during the trial? See MaxPriority('?')
.pldaps.quit: 47 control expeiment during a trial.
.pldaps.trialStates: 27 The states that an experiment runs through
.stimulus.timeLastFrame: 52
.trstart: 61
.ttime: 63 64
This function assigns these parameters:
.iFrame: 64 68
.nextFrameTime: 52
.remainingFrameTime: 63
.timing.frameStateChangeTimes: 64
.ttime: 59 61
SOURCE CODE
function p = runModularTrial(p, replay)
%runModularTrial    runs a single Trial by calling the functions defined in
%            their substruct (found by pldaps.getModules) and the function
%            defined in p.trial.pldaps.trialFunction through different states
%
% 03/2013 jly   Wrote hyperflow
% 03/2014 jk    Used jly's code to get the PLDAPS structure and frame it into a class
%               might change to ASYNC buffer flipping. but won't for now.
% 03/2016 jk    modular version
    %replay from this side is faily easy, just need to set the ttime
    %(current time in trial). User must still replace frameUpdate functions
    %to copy the correct data for the other states to use.
    if nargin<2
        replay=false;
    end
    %get all functionHandles that we want to use
    [modules,moduleFunctionHandles,moduleRequestedStates,moduleLocationInputs] = getModules(p);
    %order the framestates that we will iterate through each trial by their value
    % only positive states are frame states. And they will be called in
    % order of the value. Check comments in pldaps.getReorderedFrameStates
    % for explanations of the default states
    % negative states are special states outside of a frame (trial,
    % experiment, etc)
    [stateValue, stateName] = p.getReorderedFrameStates(p.trial.pldaps.trialStates,moduleRequestedStates);
    nStates=length(stateValue);
    runStateforModules(p,'trialSetup',modules,moduleFunctionHandles,moduleRequestedStates,moduleLocationInputs);
    %switch to high priority mode
    if p.trial.pldaps.maxPriority
        oldPriority=Priority;
        maxPriority=MaxPriority('GetSecs');
        if oldPriority < maxPriority
                Priority(maxPriority);
        end
    end
    %will be called just before the trial starts for time critical calls to
    %start data aquisition
    runStateforModules(p,'trialPrepare',modules,moduleFunctionHandles,moduleRequestedStates,moduleLocationInputs);
    %%% MAIN WHILE LOOP %%%
    %-------------------------------------------------------------------------%
    while ~p.trial.flagNextTrial && p.trial.pldaps.quit == 0
        %go through one frame by calling the modules with the different states.
        %Save the times each state is finished.
        %time of the estimated next flip
        p.trial.nextFrameTime = p.trial.stimulus.timeLastFrame+p.trial.display.ifi;
        %iterate through frame states
        for iState=1:nStates
            runStateforModules(p,stateName{iState},modules,moduleFunctionHandles,moduleRequestedStates,moduleLocationInputs);
            if replay
                p.trial.ttime=p.data{p.trial.pldaps.iTrial}.timing.frameStateChangeTimes(iState,p.trial.iFrame)+ p.trial.nextFrameTime-p.trial.display.ifi;
            else
                p.trial.ttime = GetSecs - p.trial.trstart;
            end
            p.trial.remainingFrameTime=p.trial.nextFrameTime-p.trial.ttime;
            p.trial.timing.frameStateChangeTimes(iState,p.trial.iFrame)=p.trial.ttime-p.trial.nextFrameTime+p.trial.display.ifi;
        end
        %advance to next frame, update frame index
        p.trial.iFrame = p.trial.iFrame + 1;
    end %while Trial running
    if p.trial.pldaps.maxPriority
        newPriority=Priority;
        if round(oldPriority) ~= round(newPriority)
            Priority(oldPriority);
        end
        if round(newPriority)<maxPriority
            warning('pldaps:runTrial','Thread priority was degraded by operating system during the trial.')
        end
    end
    runStateforModules(p,'trialCleanUpandSave',modules,moduleFunctionHandles,moduleRequestedStates,moduleLocationInputs);
end %runModularTrial
check here date of last update.