Description of clearCalDisplay
Home > PLDAPS > +pds > +eyelink > clearCalDisplay.m
pds.eyelink.clearCalDisplay
PURPOSE
pds.eyelink.clearCalDisplay clears the display
SYNOPSIS
function clearCalDisplay(p)
DESCRIPTION
pds.eyelink.clearCalDisplay    clears the display
CROSS-REFERENCE INFORMATION
This function calls:
pds.eyelink.calibrate pds.eyelink.calibrate start eyelink calibration routines
This function is called by:
pds.eyelink.calibrate pds.eyelink.calibrate start eyelink calibration routines
pds.eyelink.targetModeDisplay pds.eyelink.targetModeDisplay set eyelink into target mode
PARAMETER USAGE INFORMATION
This function uses these parameters:
.display.overlayptr: 9
.display.ptr: 10 12 13
.display.useOverlay: 8 create an overlay pointer.
This function assigns these parameters:
SOURCE CODE
function clearCalDisplay(p)
%pds.eyelink.clearCalDisplay    clears the display
if nargin < 1
    help pds.eyelink.calibrate
end
if p.trial.display.useOverlay
    Screen( 'FillRect',  p.trial.display.overlayptr, 0);    % clear_cal_display()
    Screen( 'Flip',  p.trial.display.ptr);
else
    Screen( 'FillRect',  p.trial.display.ptr, 0);    % clear_cal_display()
    Screen( 'Flip',  p.trial.display.ptr);
end
check here date of last update.