Description of finish
Home > PLDAPS > +pds > +eyelink > finish.m
pds.eyelink.finish
PURPOSE
pds.eyelink.finish stop recording on eyelink
SYNOPSIS
function p = finish(p)
DESCRIPTION
pds.eyelink.finish    stop recording on eyelink
 p = pds.eyelink.Finish(p)
 pds.eyelink.finish stops recording and closes the currently open edf file.
CROSS-REFERENCE INFORMATION
This function calls:
pds.eyelink.finish pds.eyelink.finish stop recording on eyelink
This function is called by:
pds.eyelink.finish pds.eyelink.finish stop recording on eyelink
@pldaps/replay replay replay a previously recorded experiment on screen
@pldaps/run run run a new experiment for a previuously created pldaps class
PARAMETER USAGE INFORMATION
This function uses these parameters:
.eyelink.edfFile: 14
.eyelink.saveEDF: 20 togge downloading of the EDF file directly after the experiment.
.eyelink.use: 12 use the eyelink moduke
.session.dir: 16
.session.file: 15
This function assigns these parameters:
SOURCE CODE
function p = finish(p)
%pds.eyelink.finish    stop recording on eyelink
%
% p = pds.eyelink.Finish(p)
% pds.eyelink.finish stops recording and closes the currently open edf file.
if nargin < 1
    help pds.eyelink.finish
    return;
end
if p.trial.eyelink.use && Eyelink('IsConnected')
    % edfFile = fullfile(dv.el.edfFileLocation, dv.el.edfFile);
    edfFile = p.trial.eyelink.edfFile;
    file=p.trial.session.file;
    dirs=p.trial.session.dir;
    Eyelink('StopRecording');
    Eyelink('CloseFile');
    % download data file
    if p.trial.eyelink.saveEDF
        try
           result=Eyelink('Receivefile',edfFile, fullfile(dirs,[file(1:end-3) 'edf']));
           if(result==-1)
              warning('pds:EyelinkGetFiles', ['receiving ' edfFile '.edf for pds file ' file ' failed!']);
           else
               display(['EDF file received: ' edfFile '.edf for pds file ' file '.']);
           end
        catch rdf
            fprintf('Problem receiving EDF data file ''%s''\n', edfFile );
        end
    end
    Eyelink('Shutdown')
end
check here date of last update.