Description of give
Home > PLDAPS > +pds > +behavior > +reward > give.m
pds.behavior.reward.give
PURPOSE
pds.behavior.reward.give(p, amount) give a certaim amount of reward
SYNOPSIS
function p = give(p, amount)
DESCRIPTION
pds.behavior.reward.give(p, amount)    give a certaim amount of reward
 handles reward for newEraSyringePumps and via TTL over datapixx. Also
 send a reward bit via datapixx (if datapixx is used).
 stores the time and amount in p.trial.behavior.reward.timeReward
 If no amount is specified, the value set in
 p.trial.behavior.reward.defaultAmount will be used
CROSS-REFERENCE INFORMATION
This function calls:
pds.datapixx.analogOut datapixxanalogOut Send a TTL pulse through the Analog Out
pds.datapixx.flipBit pds.datapixx.flipBit flip a bit on the digital out of the Datapixx
pds.newEraSyringePump.give pds.newEraSyringePump.five dispense a specified amount of volume
This function is called by:
pds.eyelink.targetModeDisplay pds.eyelink.targetModeDisplay set eyelink into target mode
@pldaps/run run run a new experiment for a previuously created pldaps class
pldapsDefaultTrialFunction
PARAMETER USAGE INFORMATION
This function uses these parameters:
.behavior.reward.defaultAmount: 9 Default amount of reward.
.behavior.reward.iReward: 29
.datapixx.use: 14 enable control of VPixx devices
.datapixx.useForReward: 15 use Datapixx to set...for a given duration....
.event.REWARD: 19
.pldaps.iTrial: 19 trial number. cannot be changed by the user
.sound.reward: 24
.sound.use: 23 toogle use of sound
.sound.useForReward: 23 toogle playing a sound for reward
This function assigns these parameters:
.behavior.reward.iReward: 28 29
.behavior.reward.timeReward: 28
SOURCE CODE
function p = give(p, amount)
%pds.behavior.reward.give(p, amount)    give a certaim amount of reward
% handles reward for newEraSyringePumps and via TTL over datapixx. Also
% send a reward bit via datapixx (if datapixx is used).
% stores the time and amount in p.trial.behavior.reward.timeReward
% If no amount is specified, the value set in
% p.trial.behavior.reward.defaultAmount will be used
    if nargin < 2
        amount = p.trial.behavior.reward.defaultAmount;
    end
    pds.newEraSyringePump.give(p,amount);
    if p.trial.datapixx.use
        if  p.trial.datapixx.useForReward
            pds.datapixx.analogOut(amount);
        end
        %%flag
        pds.datapixx.flipBit(p.trial.event.REWARD,p.trial.pldaps.iTrial);
    end
    %%sound
    if p.trial.sound.use && p.trial.sound.useForReward
        PsychPortAudio('Start', p.trial.sound.reward);
    end
    %% store data
    p.trial.behavior.reward.timeReward(:,p.trial.behavior.reward.iReward) = [GetSecs amount];
    p.trial.behavior.reward.iReward = p.trial.behavior.reward.iReward + 1;
check here date of last update.