Description of flipBit
Home > PLDAPS > +pds > +datapixx > flipBit.m
pds.datapixx.flipBit
PURPOSE
pds.datapixx.flipBit flip a bit on the digital out of the Datapixx
SYNOPSIS
function timings=flipBit(bit,trial)
DESCRIPTION
pds.datapixx.flipBit    flip a bit on the digital out of the Datapixx
 pds.datapixx.flipBit flips a bit on the digital out of the Datapixx
 box and back.
 NOTE: This code is optimized to use with the Plexon omniplex system.
 We are using it it stobe only mode and thus simply forward the command to
 pds.datapixx.stobe
 (c) jk 2015
CROSS-REFERENCE INFORMATION
This function calls:
pds.datapixx.strobe pds.datapixx.strobe strobes a 16 Bit word from the datapixx
This function is called by:
pds.behavior.reward.give pds.behavior.reward.give(p, amount) give a certaim amount of reward
@pldaps/replay replay replay a previously recorded experiment on screen
pldapsDefaultTrialFunction
PARAMETER USAGE INFORMATION
This function uses these parameters:
This function assigns these parameters:
SOURCE CODE
function timings=flipBit(bit,trial)
%pds.datapixx.flipBit    flip a bit on the digital out of the Datapixx
%
% pds.datapixx.flipBit flips a bit on the digital out of the Datapixx
% box and back.
%
% NOTE: This code is optimized to use with the Plexon omniplex system.
% We are using it it stobe only mode and thus simply forward the command to
% pds.datapixx.stobe
%
% (c) jk 2015
if nargout==0
    pds.datapixx.strobe(trial,2^(bit-1));
else
    timings=pds.datapixx.strobe(trial,2^(bit-1));
end
check here date of last update.